### ISSUE TITLE
Azure Pipeline Yaml

### ISSUE THREAD

**Issue by JoeGarzaEmerson** [christiansparre/HelloContainerApps#2]
Can you share the azure.pipelines.yml?

**Comment by JoeGarzaEmerson** [comment]
Im guessing this?

`
trigger:
- master

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: '<your-connection-name>'
  resourceGroupName: 'exampleRG'
  location: '<your-resource-group-location>'
  templateFile: './main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    overrideParameters: '-storageAccountType Standard_LRS'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
`

**Comment by christiansparre** [comment]
Looks about right. Never played around with deploying bicep in Azure Pipelines
